@startuml
actor Gebruiker
participant WebApp
participant FlightController
participant FlightService
participant IFlightDataStrategy
participant AeroDataBoxProvider
participant FlightRadar24Provider

Gebruiker -> WebApp : zoekDichtstbijzijndeVliegveld(locatie)
WebApp -> FlightController : fetchNearbyAirports(locatie)
FlightController -> FlightService : fetchNearbyAirports(locatie)
FlightService -> IFlightDataStrategy : getNearestAirport(locatie)

alt Strategy: AeroDataBoxProvider
    IFlightDataStrategy -> AeroDataBoxProvider : getNearestAirport(locatie)
    AeroDataBoxProvider --> IFlightDataStrategy : vliegveldData
end

alt Strategy: FlightRadar24Provider
    IFlightDataStrategy -> FlightRadar24Provider : getNearestAirport(locatie)
    FlightRadar24Provider --> IFlightDataStrategy : vliegveldData
end

IFlightDataStrategy --> FlightService : vliegveldData
FlightService --> FlightController : vliegveldData
FlightController --> WebApp : vliegveldData
WebApp --> Gebruiker : Dichtstbijzijnde vliegveld tonen
@enduml
