@startuml
actor Gebruiker
participant WebApp
participant FlightController
participant FlightService
participant IFlightDataStrategy
participant AeroDataBoxProvider
participant FlightRadar24Provider

Gebruiker -> WebApp : searchNearestAirport(locatie)
WebApp -> FlightController : nearestAirport = fetchNearbyAirports(locatie)
FlightController -> FlightService : nearestAirport = fetchNearbyAirports(locatie)
FlightService -> IFlightDataStrategy : nearestAirport = getNearestAirport(locatie)

alt Strategy: AeroDataBoxProvider
    IFlightDataStrategy -> AeroDataBoxProvider :nearestAirport =  getNearestAirport(locatie)
    AeroDataBoxProvider --> IFlightDataStrategy : nearestAirport
end

alt Strategy: FlightRadar24Provider
    IFlightDataStrategy -> FlightRadar24Provider : nearestAirport = getNearestAirport(locatie)
    FlightRadar24Provider --> IFlightDataStrategy : nearestAirport
end

IFlightDataStrategy --> FlightService : nearestAirport
FlightService --> FlightController : nearestAirport
FlightController --> WebApp : nearestAirport
WebApp --> Gebruiker : Show nearest airport
@enduml
