@startuml
'https://plantuml.com/sequence-diagram

actor Gebruiker
participant WebApp
participant FlightController
participant FlightService
participant IFlightDataStrategy
participant AeroDataBoxProvider
participant FlightRadar24Provider

Gebruiker -> WebApp : searchFlights()
WebApp -> FlightController : fetchFlightData(flightNumber)
FlightController -> FlightService : fetchFlightData(flightNumber)
FlightService -> IFlightDataStrategy : getFlightData(flightNumber)

alt Strategy: AeroDataBoxProvider
    IFlightDataStrategy -> AeroDataBoxProvider : getFlightData(flightNumber)
    AeroDataBoxProvider --> IFlightDataStrategy : flightData
end

alt Strategy: FlightRadar24Provider
    IFlightDataStrategy -> FlightRadar24Provider : getFlightData(flightNumber)
    FlightRadar24Provider --> IFlightDataStrategy : flightData
end

IFlightDataStrategy --> FlightService : flightData
FlightService --> FlightController : flightData
FlightController --> WebApp : flightData
WebApp --> Gebruiker : vluchtinformatie tonen
@enduml
