@startuml
'https://plantuml.com/class-diagram

class WebApp {
    +searchFlights(flightQuery: FlightQuery): FlightResults
    +getFlightStatus(flightDetails: FlightDetails): FlightStatus
}

class FlightController {
    +fetchFlightData(flightQuery: FlightQuery): FlightResults
}

class StrategyController {
    +setCurrentStrategy(strategy: String)
    +getCurrentStrategy(): String
}

class FlightService {
    -flightDataStrategy: FlightDataStrategy
    +setFlightDataStrategy(strategy: FlightDataStrategy)
    +fetchFlightData(flightQuery: FlightQuery): FlightResults
}

class StrategyService {
    -StrategyConfig: StrategyConfig
    +setCurrentStrategy(strategy: String)
    +getCurrentStrategy(): String
}

interface FlightDataStrategy {
    +fetchFlightData(flightQuery: FlightQuery): FlightResults
}

class AeroDataBoxProvider {
    +fetchFlightData(flightQuery: FlightQuery): FlightResults
    +fetchNearbyAirports(airport: String): AirportResults
}

class FlightRadar24Provider {
    +fetchFlightData(flightQuery: FlightQuery): FlightResults
    +fetchNearbyAirports(airport: String): AirportResults
}

class StrategyConfig {
    -currentStrategy: String
    +setCurrentStrategy(strategy: String)
    +getCurrentStrategy(): String
}

' Relationships
WebApp --> FlightController : "Uses"
WebApp --> StrategyController : "Uses"
FlightController --> FlightService : "Uses"
StrategyController --> StrategyService : "Uses"
FlightService --> FlightDataStrategy : "Uses"
StrategyService --> StrategyConfig : "Uses"

FlightDataStrategy <|-- AeroDataBoxProvider
FlightDataStrategy <|-- FlightRadar24Provider

@enduml
