@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include <C4/C4_Container>
top to bottom direction

skinparam {
    rectangle {
        StereotypeFontSize 0
        StereotypeFontColor white
    }
}

Person(traveller, "[Reiziger]", "Een reiziger die een reis met meerdere bestemmingen wil samenstellen.")
Person(admin, "[Administrator]", "Beheerder")

System(triptop, "[Triptop]", "Helpt reizigers een trip te organiseren met meerdere bestemmingen.")

System_Ext(identity_provider_api, "[Identity Provider API]", "Biedt inlogmogelijkheden via onder andere Apple, Google en Microsoft.", $link="https://developer.okta.com/docs/api/openapi/okta-management/management/tag/IdentityProvider/")
System_Ext(demand_api, "[Demand API]", "Booking.com's API voor verblijf, autoverhuur, vluchten\*, accommodaties\* en luchthaventaxi's\*.", $link="https://developers.booking.com/demand/docs/open-api/demand-api")
System_Ext(mollie_api, "[Mollie API]", "Eén platform voor betalingen via onder andere Klarna, iDEAL, Apple Pay en PayPal.", $link="https://www.mollie.com/nl/")
System_Ext(google_maps_api, "[Google Maps Platform]", "Google's API voor kaarten, routes en plekken.", $link="https://developers.google.com/maps")
System_Ext(all_aboard_api, "[The API]", "Biedt boek- en beheermogelijkheden voor treinreizen binnen Europa.", $link="https://allaboard.eu/api-solution")
System_Ext(aeroDataBox_api, "[AeroDataBox API]", "Biedt vliegvelden, vluchttijden en vluchtroutes wereldwijd.", $link="https://rapidapi.com/aedbx-aedbx/api/aerodatabox")
System_Ext(grubhub_api, "[Grubhub]", "Biedt bezorg en afhaalmogelijkheid voor eten en drinken bij diverse restaurants.", $link="https://www.grubhub.com/")

Rel(traveller, triptop, "maakt reisplan met")
Rel(admin, triptop, "beheert")

Rel(triptop, identity_provider_api, "zorgt voor inlogfunctionaliteit met")
Rel(triptop, demand_api, "suggereert verblijven met")
Rel(triptop, mollie_api, "handelt betalingen af met")
Rel(triptop, google_maps_api, "bepaalt routes tussen bestemmingen met")
Rel(triptop, all_aboard_api, "beheert en houdt treinreizen bij met")
Rel(triptop, aeroDataBox_api, "beheert en houdt vluchten bij met")
Rel(triptop, grubhub_api, "stelt eet- en drinkmogelijkheden voor met")

SHOW_LEGEND(TRUE)
@enduml